name: Build and Push QEMU Images

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and push 'box' image
        uses: docker/build-push-action@v5
        with:
          context: ./box
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:box

      - name: Build and push 'privatebox' image
        uses: docker/build-push-action@v5
        with:
          context: ./privatebox
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:privatebox